from . import (DLSTM, DTGRU, FITS, LSTM, MCN, MCTAN, MICN, RSN, TCN, TR_LT,
               AdaNet, Autoformer, Crossformer, DeepPLS, DLformer, DLinear,
               ETSformer, FEDformer, FiLM, FreTS, Informer, Koopa, LightTS,
               MambaSimple, Nonstationary_Transformer, PatchTST, Pathformer,
               PAttn, Pyraformer, Reformer, SCINet, SegRNN, TiDE, TimeMixer,
               TimesNet, TimeXer, Transformer, Triformer, TSMixer,
               iTransformer)

MODEL_DICT = {
    'TimesNet': TimesNet,
    'Autoformer': Autoformer,
    'Transformer': Transformer,
    'Nonstationary_Transformer': Nonstationary_Transformer,
    'DLinear': DLinear,
    'FEDformer': FEDformer,
    'Informer': Informer,
    'LightTS': LightTS,
    'Reformer': Reformer,
    'ETSformer': ETSformer,
    'PatchTST': PatchTST,
    'Pyraformer': Pyraformer,
    'MICN': MICN,
    'Crossformer': Crossformer,
    'FiLM': FiLM,
    'iTransformer': iTransformer,
    'LSTM': LSTM,
    'TCN': TCN,
    'FreTS': FreTS,
    'PAttn': PAttn,
    'SegRNN': SegRNN,
    'TSMixer': TSMixer,
    'Koopa': Koopa,
    'SCINet': SCINet,
    'TiDE': TiDE,
    'TimeMixer': TimeMixer,
    'TimeXer': TimeXer,
    'DeepPLS': DeepPLS,
    'FITS': FITS,
    'Pathformer': Pathformer,
    'Triformer': Triformer,
    'MCTAN': MCTAN,
    'DLformer': DLformer,
    'DLSTM': DLSTM,
    'RSN': RSN,
    'DTGRU': DTGRU,
    'AdaNet': AdaNet,
    'TR_LT': TR_LT,
    'MCN': MCN,
    'Mamba': MambaSimple
}
